services:
  licensing-vitrine:
    container_name: licensing-vitrine
    build:
      context: ./vitrine
      dockerfile: Dockerfile.dev
    environment:
      - APP_URL=${APP_URL}
      - NEXT_API_URL=${API_URL}
      - NEXT_PUBLIC_API_URL=${API_URL}
    volumes:
      - ./vitrine:/app
      - licensing_vitrine_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - licensing-server

  licensing-server:
    container_name: licensing-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - APP_URL=${APP_URL}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_API_VERSION=${STRIPE_API_VERSION}
    volumes:
      - ./server:/app
      - licensing_server_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - licensing-mongo

  licensing-mongo:
    container_name: licensing-mongo
    image: mongo:latest
    volumes:
      - licensing_mongo_data:/data/db
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf:ro
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    ports:
      - "27018:27017"
    restart: unless-stopped

volumes:
  licensing_vitrine_node_modules:
  licensing_server_node_modules:
  licensing_mongo_data:
